homePage:
    path:     /rz-admin{trailingSlash}
    defaults: { _controller: Themes\Rozier\Controllers\NodesController::indexAction }
    requirements: { trailingSlash : "[/]{0,1}" }
nodesHomePage:
    path:     /rz-admin/nodes{trailingSlash}
    defaults: { _controller: Themes\Rozier\Controllers\NodesController::indexAction }
    requirements: { trailingSlash : "[/]{0,1}" }
nodesEditTranslatedPage:
    path:     /rz-admin/nodes/edit/{node_id}/{translation_id}{trailingSlash}
    defaults: { _controller: Themes\Rozier\Controllers\NodesController::editAction }
    requirements: { trailingSlash : "[/]{0,1}", node_id : "[0-9]+", translation_id : "[0-9]+" }
nodesEditPage:
    path:     /rz-admin/nodes/edit/{node_id}{trailingSlash}
    defaults: { _controller: Themes\Rozier\Controllers\NodesController::editAction }
    requirements: { trailingSlash : "[/]{0,1}", node_id : "[0-9]+" }
nodesTreePage:
    path:     /rz-admin/nodes/tree/{node_id}{trailingSlash}
    defaults: { _controller: Themes\Rozier\Controllers\NodesController::treeAction }
    requirements: { trailingSlash : "[/]{0,1}", node_id : "[0-9]+" }
nodesAddPage:
    path:     /rz-admin/nodes/add/{node_type_id}/{translation_id}{trailingSlash}
    defaults: { _controller: Themes\Rozier\Controllers\NodesController::addAction }
    requirements: { trailingSlash : "[/]{0,1}", node_type_id : "[0-9]+", translation_id : "[0-9]+" }
nodesDeletePage:
    path:     /rz-admin/nodes/delete/{node_id}{trailingSlash}
    defaults: { _controller: Themes\Rozier\Controllers\NodesController::deleteAction }
    requirements: { trailingSlash : "[/]{0,1}", node_id : "[0-9]+" }
noAction:
    path:     /rz-admin/no{trailingSlash}
    defaults: { _controller: Themes\Rozier\Controllers\NodesController::noAction }
    requirements: { trailingSlash : "[/]{0,1}" }