# Roadiz travis setup
# Ambroise Maupate
language: php
sudo: required
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - env: DB=sqlite

env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite

install:
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS roadiz_tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS roadiz_tests_tmp;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database roadiz_tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database roadiz_tests_tmp;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then cp conf/config.pgsql.travis.yml conf/config.yml; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS roadiz_tests_tmp;create database IF NOT EXISTS roadiz_tests;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then cp conf/config.mysql.travis.yml conf/config.yml; fi"
  - sh -c "if [ '$DB' = 'sqlite' ]; then cp conf/config.sqlite.travis.yml conf/config.yml; fi"
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction


script:
  - php bin/roadiz orm:schema-tool:create -n --env=install
  - php bin/roadiz install -n --env=install
  - php bin/roadiz themes:install -n "/Themes/DefaultTheme/DefaultThemeApp"
  - php bin/roadiz themes:install -n --data "/Themes/DefaultTheme/DefaultThemeApp"
  - php bin/roadiz cache:clear --env=install
  - php bin/roadiz orm:schema-tool:update -n --force
  - php bin/roadiz themes:install -n --nodes "/Themes/DefaultTheme/DefaultThemeApp"
  - php bin/roadiz cache:clear --env=install
  - php bin/roadiz cache:clear --env=test
  - php bin/roadiz orm:schema-tool:drop --force
  - ENABLE_SECOND_LEVEL_CACHE=0 php bin/phpunit -v --bootstrap=tests/bootstrap.php --coverage-clover ./build/logs/clover.xml tests/
  - bin/phpcs --report=full --report-file=./report.txt --extensions=php --warning-severity=0 --standard=PSR2 --ignore=*/node_modules/*,*/.AppleDouble,*/vendor/*,*/cache/*,*/gen-src/*,*/tests/*,*/bin/* -p ./

after_success:
  - travis_retry php bin/coveralls -v

notifications:
  webhooks: https://coveralls.io/webhook?repo_token=auwcnYiFOeFFp0vxd4Tx158ToE5YvMAHg
