# Roadiz travis setup
# Ambroise Maupate
language: php
sudo: required
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
    - php: hhvm-nightly

env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite

before_script:
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS roadiz_tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS roadiz_tests_tmp;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database roadiz_tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database roadiz_tests_tmp;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then cp conf/config.pgsql.travis.yml conf/config.yml; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS roadiz_tests_tmp;create database IF NOT EXISTS roadiz_tests;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then cp conf/config.mysql.travis.yml conf/config.yml; fi"
  - sh -c "if [ '$DB' = 'sqlite' ]; then cp conf/config.sqlite.travis.yml conf/config.yml; fi"
  - composer self-update
  - composer install --no-interaction
  - php bin/roadiz orm:schema-tool:create -n --env=install
  - php bin/roadiz install -n --env=install
  - php bin/roadiz core:themes:install -n "Themes\\DefaultTheme\\DefaultThemeApp"
  - php bin/roadiz orm:schema-tool:update -n --force
  - php bin/roadiz core:themes:install -n --data "Themes\\DefaultTheme\\DefaultThemeApp"
  - php bin/roadiz cache -a --env=install
  - php bin/roadiz cache -a --env=test

script:
  - ENABLE_SECOND_LEVEL_CACHE=0 bin/phpunit -v --bootstrap=tests/bootstrap.php --coverage-clover ./build/logs/clover.xml tests/
  - bin/phpcs --report=full --report-file=./report.txt --extensions=php --warning-severity=0 --standard=PSR2 --ignore=*/node_modules/*,*/.AppleDouble,*/vendor/*,*/cache/*,*/gen-src/*,*/tests/*,*/bin/* -p ./

after_script:
  - php bin/coveralls -v
