# This route is required!
homePage:
    path:     /
    defaults: { _controller: Themes\DefaultTheme\DefaultThemeApp::homeAction }
homePageLocale:
    path:     /{_locale}
    defaults: { _controller: Themes\DefaultTheme\DefaultThemeApp::homeAction }
    requirements:
        # Use every 2 letter codes (quick and dirty)
        _locale: "[a-z]{2}"

contactPage:
    path:     /contact
    defaults: { _controller: Themes\DefaultTheme\Controllers\ContactController::indexAction }
contactPageLocale:
    path:     /{_locale}/contact
    defaults: { _controller: Themes\DefaultTheme\Controllers\ContactController::indexAction }
    requirements:
        # Use every 2 letter codes (quick and dirty)
        _locale: "[a-z]{2}"

feedRSS:
    path:     /feed
    defaults: { _controller: Themes\DefaultTheme\Controllers\FeedController::indexAction }
sitemap:
    path:     /sitemap.xml
    defaults: { _controller: Themes\DefaultTheme\Controllers\SitemapController::indexAction }
defaultRemoveTrailingSlash:
    path: /{url}
    defaults: { _controller: Themes\DefaultTheme\DefaultThemeApp::removeTrailingSlashAction }
    requirements:
        url: .*/$
    methods: [GET]

# This page is created from DefaultTheme
# to show you how to extend backoffice features.
adminTestPage:
    path:     /rz-admin/test # Setting your path behind rz-admin will activate Firewall
    defaults: { _controller: Themes\DefaultTheme\Controllers\AdminController::listAction }
