# This route is required!
homePage:
    path:     /
    defaults: { _controller: Themes\DefaultTheme\DefaultApp::homeAction }
homePageLocale:
    path:     /{_locale}
    defaults: { _controller: Themes\DefaultTheme\DefaultApp::homeAction }
    requirements:
        _locale: "[a-z]{2}"
feedRSS:
    path:     /feed
    defaults: { _controller: Themes\DefaultTheme\Controllers\FeedController::indexAction }
sitemap:
    path:     /sitemap.xml
    defaults: { _controller: Themes\DefaultTheme\Controllers\SitemapController::indexAction }
defaultRemoveTrailingSlash:
    path: /{url}
    defaults: { _controller: Themes\DefaultTheme\DefaultApp::removeTrailingSlashAction }
    requirements:
        url: .*/$
    methods: [GET]