# This route is required!
homePage:
    path:     /
    defaults: { _controller: Themes\DefaultTheme\DefaultThemeApp::homeAction }
homePageLocale:
    path:     /{_locale}
    defaults:
        _controller: Themes\DefaultTheme\DefaultThemeApp::homeAction
        _locale: en
    requirements:
        _locale: "[a-z]{2}_?[A-Z]{0,2}"

contactPage:
    path:     /contact
    defaults: { _controller: Themes\DefaultTheme\Controllers\ContactController::indexAction }
contactPageLocale:
    path:     /{_locale}/contact
    defaults: { _controller: Themes\DefaultTheme\Controllers\ContactController::indexAction }
    requirements:
        _locale: "[a-z]{2}_?[A-Z]{0,2}"

feedRSS:
    path:     /feed
    defaults: { _controller: Themes\DefaultTheme\Controllers\FeedController::indexAction }
sitemap:
    path:     /sitemap.xml
    defaults: { _controller: Themes\DefaultTheme\Controllers\SitemapController::indexAction }
defaultRemoveTrailingSlash:
    path: /{url}
    defaults: { _controller: Themes\DefaultTheme\DefaultThemeApp::removeTrailingSlashAction }
    requirements:
        url: .*/$
    methods: [GET]
