# Home page
installHomePage:
    path:     /
    defaults: { _controller: Themes\Install\InstallApp::indexAction }
installHomePageRedirect:
    path:     /install
    defaults: { _controller: Themes\Install\InstallApp::redirectIndexAction }
installCheckPage:
    path:     /install/check-requirements
    defaults: { _controller: Themes\Install\InstallApp::requirementsAction }
installDatabasePage:
    path:     /install/database
    defaults: { _controller: Themes\Install\InstallApp::databaseAction }
installDatabaseDonePage:
    path:     /install/database/done
    defaults: { _controller: Themes\Install\InstallApp::databaseDoneAction }
installImportPage:
    path:     /install/import
    defaults: { _controller: Themes\Install\InstallApp::importAction }
installImportSettings:
    path:     /install/import/settings
    defaults: { _controller: RZ\Renzo\CMS\Controllers\ImportController::importSettingsAction }
installImportGroups:
    path:     /install/import/groups
    defaults: { _controller: RZ\Renzo\CMS\Controllers\ImportController::importGroupsAction }
installImportRoles:
    path:     /install/import/roles
    defaults: { _controller: RZ\Renzo\CMS\Controllers\ImportController::importRolesAction }
installUserPage:
    path:     /install/user
    defaults: { _controller: Themes\Install\InstallApp::userAction }
installUserSummaryPage:
    path:     /install/user/summary/{userId}
    defaults: { _controller: Themes\Install\InstallApp::userSummaryAction }
    requirements: { userId : "[0-9]+" }
installThemesPage:
    path:     /install/themes
    defaults: { _controller: Themes\Install\InstallApp::themesAction }
installDonePage:
    path:     /install/done
    defaults: { _controller: Themes\Install\InstallApp::doneAction }
installFailedPage:
    path:     /install/failed
    defaults: { _controller: Themes\Install\InstallApp::failedAction }
removeTrailingSlash:
    path: /{url}
    defaults: { _controller:  Themes\Install\InstallApp::removeTrailingSlashAction }
    requirements:
        url: .*/$
    methods: [GET]
