# Home page
installHomePage:
    path:     /
    defaults: { _controller: Themes\Install\InstallApp::indexAction }
installHomePageRedirect:
    path:     /install
    defaults: { _controller: Themes\Install\InstallApp::redirectIndexAction }
installCheckPage:
    path:     /install/check-requirements
    defaults: { _controller: Themes\Install\InstallApp::requirementsAction }
installDatabasePage:
    path:     /install/database
    defaults: { _controller: Themes\Install\InstallApp::databaseAction }
installDatabaseSchemaPage:
    path:     /install/database/schema
    defaults: { _controller: Themes\Install\InstallApp::databaseSchemaAction }
# installImportPage:
#     path:     /install/import
#     defaults: { _controller: Themes\Install\InstallApp::importAction }
installImportSettings:
    path:     /install/import/settings/{filename}/{id}
    defaults: { _controller: RZ\Renzo\CMS\Controllers\ImportController::importSettingsAction }
    requirements:
        filename: "^[a-zA-Z_/.]+$"
        id: "[0-9]+"
installImportGroups:
    path:     /install/import/groups/{filename}/{id}
    defaults: { _controller: RZ\Renzo\CMS\Controllers\ImportController::importGroupsAction }
    requirements:
        filename: "^[a-zA-Z_/.]+$"
        id: "[0-9]+"
installImportRoles:
    path:     /install/import/roles/{filename}/{id}
    defaults: { _controller: RZ\Renzo\CMS\Controllers\ImportController::importRolesAction }
    requirements:
        filename: "^[a-zA-Z_/.]+$"
        id: "[0-9]+"
installImportNodes:
    path:     /install/import/nodes/
    defaults: { _controller: RZ\Renzo\CMS\Controllers\ImportController::importNodesAction }
    # requirements:
    #     filename: "^[a-zA-Z_/.]+$"
    #     id: "[0-9]+"
installImportNodeTypes:
    path:     /install/import/nodetypes/{filename}/{id}
    defaults: { _controller: RZ\Renzo\CMS\Controllers\ImportController::importNodeTypesAction }
    requirements:
        filename: "^[a-zA-Z_/.]+$"
        id: "[0-9]+"
installImportNodeTypesPage:
    path:     /install/import/nodetypes/{id}
    defaults: { _controller: Themes\Install\InstallApp::nodeTypesAction }
    requirements: { id : "[0-9]+" }
installUserPage:
    path:     /install/user
    defaults: { _controller: Themes\Install\InstallApp::userAction }
installUserSummaryPage:
    path:     /install/user/summary/{userId}
    defaults: { _controller: Themes\Install\InstallApp::userSummaryAction }
    requirements: { userId : "[0-9]+" }
installThemesPage:
    path:     /install/themes
    defaults: { _controller: Themes\Install\InstallApp::themesAction }
installDonePage:
    path:     /install/done
    defaults: { _controller: Themes\Install\InstallApp::doneAction }
installFailedPage:
    path:     /install/failed
    defaults: { _controller: Themes\Install\InstallApp::failedAction }
installUpdateSchema:
    path:     /install/update
    defaults: { _controller: Themes\Install\InstallApp::updateSchemaAction }
removeTrailingSlash:
    path: /{url}
    defaults: { _controller:  Themes\Install\InstallApp::removeTrailingSlashAction }
    requirements:
        url: .*/$
    methods: [GET]
