---
appNamespace: "chooseAnUniqueNameForYourApp"
install: true
devMode: true
timezone: "Europe/Paris"
doctrine:
    driver: "pdo_mysql"
    host: "localhost"
    user: ""
    password: ""
    dbname: ""
# http://symfony.com/doc/current/reference/configuration/doctrine.html#caching-drivers
# If null or empty, Roadiz will try to detect best cache driver available
cacheDriver:
    type: null
    host: null
    port: null
security:
    secret: "change#this#secret#very#important"
mailer:
    type: ""
    host: "localhost"
    port: 25
    encryption: false
    username: ""
    password: ""
entities:
    - "src/Roadiz/Core/Entities"
    - "src/Roadiz/Core/AbstractEntities"
    - "gen-src/GeneratedNodeSources"
# Lifetime of remember-me cookie in seconds (30 days)
rememberMeLifetime: 2592000
serviceProviders:
    - \RZ\Roadiz\Core\Services\BackofficeServiceProvider
    - \RZ\Roadiz\Core\Services\DoctrineServiceProvider
    - \RZ\Roadiz\Core\Services\EmbedDocumentsServiceProvider
    - \RZ\Roadiz\Core\Services\EntityApiServiceProvider
    - \RZ\Roadiz\Core\Services\FormServiceProvider
    - \RZ\Roadiz\Core\Services\MailerServiceProvider
    - \RZ\Roadiz\Core\Services\RoutingServiceProvider
    - \RZ\Roadiz\Core\Services\SecurityServiceProvider
    - \RZ\Roadiz\Core\Services\SolrServiceProvider
    - \RZ\Roadiz\Core\Services\ThemeServiceProvider
    - \RZ\Roadiz\Core\Services\TranslationServiceProvider
    - \RZ\Roadiz\Core\Services\TwigServiceProvider
