---
appNamespace: "chooseAnUniqueNameForYourAppMySQL"
timezone: "Europe/Paris"
doctrine:
    driver: "pdo_mysql"
    host: "localhost"
    user: "root"
    password: ""
    dbname: "roadiz_tests"
    charset: 'utf8'
    options:
        1002: "SET NAMES 'UTF8'"
security:
    secret: "change#this#secret#very#important"
cacheDriver:
    type: ~
    host: ~
    port: ~
mailer:
    type: ~
    host: "localhost"
    port: 25
    encryption: ~
    username: ""
    password: ""
entities:
    - "src/Roadiz/Core/Entities"
    - "vendor/roadiz/models/src/Roadiz/Core/AbstractEntities"
    - "gen-src/GeneratedNodeSources"
# Lifetime of remember-me cookie in seconds (30 days)
rememberMeLifetime: 2592000
additionalServiceProviders: []
additionalCommands: []
assetsProcessing:
    driver: gd
    defaultQuality: 90
    # pixel size limit () after roadiz
    # should create a smaller copy.
    maxPixelSize: 1920
    jpegoptimPath: ~
    pngquantPath: ~

