---
appNamespace: "chooseAnUniqueNameForYourApp"
install: true
devMode: true
timezone: "Europe/Paris"
doctrine:
    driver: "pdo_mysql"
    host: "localhost"
    user: ""
    password: ""
    dbname: ""
# http://symfony.com/doc/current/reference/configuration/doctrine.html#caching-drivers
# If null or empty, Roadiz will try to detect best cache driver available
cacheDriver:
    type: null
    host: null
    port: null
security:
    secret: "change#this#secret#very#important"
mailer:
    type: ""
    host: "localhost"
    port: 25
    encryption: false
    username: ""
    password: ""
entities:
    - "src/Roadiz/Core/Entities"
    - "src/Roadiz/Core/AbstractEntities"
    - "gen-src/GeneratedNodeSources"
