---
appNamespace: "chooseAnUniqueNameForYourAppPgSQL"
install: true
devMode: true
timezone: "Europe/Paris"
doctrine:
    driver: "pdo_pgsql"
    host: "localhost"
    user: "postgres"
    password: ""
    dbname: "roadiz_tests"
security:
    secret: "change#this#secret#very#important"
cacheDriver:
    type: null
    host: null
    port: null
mailer:
    type: ""
    host: "localhost"
    port: 25
    encryption: false
    username: ""
    password: ""
entities:
    - "src/Roadiz/Core/Entities"
    - "src/Roadiz/Core/AbstractEntities"
    - "gen-src/GeneratedNodeSources"
