---
appNamespace: "pgsql_travis_test"
timezone: "Europe/Paris"
doctrine:
    driver: "pdo_pgsql"
    host: "localhost"
    user: "postgres"
    password: ""
    dbname: "roadiz_tests"
    charset: utf8mb4
    default_table_options:
        charset: utf8mb4
        collate: utf8mb4_unicode_ci
security:
    secret: "pgsql_travis_test"
cacheDriver:
    type: array
    host: ~
    port: ~
mailer:
    type: ~
    host: "localhost"
    port: 25
    encryption: ~
    username: ""
    password: ""
themes:
    - classname: \Themes\DefaultTheme\DefaultThemeApp
      hostname: '*'
      routePrefix: ''
entities:
    - "src/Roadiz/Core/Entities"
    - "vendor/roadiz/models/src/Roadiz/Core/AbstractEntities"
    - "gen-src/GeneratedNodeSources"
# Lifetime of remember-me cookie in seconds (30 days)
rememberMeLifetime: 2592000
additionalServiceProviders: []
additionalCommands:
    - \Themes\DefaultTheme\Commands\DefaultThemeCommand
assetsProcessing:
    driver: gd
    defaultQuality: 90
    # pixel size limit () after roadiz
    # should create a smaller copy.
    maxPixelSize: 1920
    jpegoptimPath: ~
    pngquantPath: ~

