---
appNamespace: "chooseAnUniqueNameForYourAppSQLite"
install: true
devMode: true
timezone: "Europe/Paris"
doctrine:
    driver: "pdo_sqlite"
    user: "root"
    password: ""
    path: "conf/travis.db"
security:
    secret: "change#this#secret#very#important"
mailer:
    type: ""
    host: "localhost"
    port: 25
    encryption: false
    username: ""
    password: ""
entities:
    - "src/Roadiz/Core/Entities"
    - "src/Roadiz/Core/AbstractEntities"
    - "gen-src/GeneratedNodeSources"
