providers:
    - \RZ\Roadiz\Core\Services\BackofficeServiceProvider
    - \RZ\Roadiz\Core\Services\YamlConfigurationServiceProvider
    - \RZ\Roadiz\Core\Services\DoctrineServiceProvider
    - \RZ\Roadiz\Core\Services\EmbedDocumentsServiceProvider
    - \RZ\Roadiz\Core\Services\EntityApiServiceProvider
    - \RZ\Roadiz\Core\Services\FormServiceProvider
    - \RZ\Roadiz\Core\Services\MailerServiceProvider
    - \RZ\Roadiz\Core\Services\RoutingServiceProvider
    - \RZ\Roadiz\Core\Services\SecurityServiceProvider
    - \RZ\Roadiz\Core\Services\SolrServiceProvider
    - \RZ\Roadiz\Core\Services\ThemeServiceProvider
    - \RZ\Roadiz\Core\Services\TranslationServiceProvider
    - \RZ\Roadiz\Core\Services\TwigServiceProvider
