homePage:
    path:     /rz-admin
    defaults: { _controller: RZ\Renzo\CMS\Controllers\NodesController::indexAction }
nodesHomePage:
    path:     /rz-admin/nodes
    defaults: { _controller: RZ\Renzo\CMS\Controllers\NodesController::indexAction }
nodesEditTranslatedPage:
    path:     /rz-admin/nodes/edit/{node_id}/{translation_id}
    defaults: { _controller: RZ\Renzo\CMS\Controllers\NodesController::editAction }
nodesEditPage:
    path:     /rz-admin/nodes/edit/{node_id}
    defaults: { _controller: RZ\Renzo\CMS\Controllers\NodesController::editAction }
nodesAddPage:
    path:     /rz-admin/nodes/add/{node_type_id}
    defaults: { _controller: RZ\Renzo\CMS\Controllers\NodesController::addAction }
nodesDeletePage:
    path:     /rz-admin/nodes/delete/{node_id}
    defaults: { _controller: RZ\Renzo\CMS\Controllers\NodesController::deleteAction }
noAction:
    path:     /rz-admin/no
    defaults: { _controller: RZ\Renzo\CMS\Controllers\NodesController::noAction }