#
# Fonts serving
#
FontFile:
    path:     /fonts/files/{filename}_{variant}.{extension}
    defaults: { _controller: \RZ\Roadiz\CMS\Controllers\AssetsController::fontFileAction }
    requirements: { filename: "[a-zA-Z0-9\-_]+", variant: "[0-9]", extension: "[a-z0-9]+" }
FontFaceCSS:
    path:     /font-faces.css
    defaults: { _controller: \RZ\Roadiz\CMS\Controllers\AssetsController::fontFacesAction }
#
# InterventionRequest is hard coded before run app
#
interventionRequestProcess:
    path:     /assets/{queryString}/{filename}
    defaults: { _controller: \RZ\Roadiz\CMS\Controllers\AssetsController::interventionRequestAction }
    requirements: { queryString : "[a-zA-Z:0-9\-]+", filename : "[a-zA-Z0-9\-_\.\/]+" }
