#
# Contact form handling
#
contactFormLocaleAction:
    path:     /{_locale}/submit-form/contact
    defaults: { _controller: \RZ\Roadiz\CMS\Controllers\EntryPointsController::contactFormAction }
    requirements:
        # Use every 2 letter codes (quick and dirty)
        _locale: "[a-z]{2}"

customFormSendAction:
    path:     /custom-form/{customFormId}
    defaults: { _controller: \RZ\Roadiz\CMS\Controllers\CustomFormController::addAction }
    requirements:
        customFormId: "[0-9]+"
customFormSentAction:
    path:     /custom-form/{customFormId}/sent
    defaults: { _controller: \RZ\Roadiz\CMS\Controllers\CustomFormController::sentAction }
    requirements:
        customFormId: "[0-9]+"
